In [1]:
import numpy as np

In [ ]:
#1. import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print("shape of a:",a.shape)
print("current value:",a[0], a[1], a[2])
a[0] = 5
print(a)
arr=np.linalg.matrix_rank([1,2,3])
print("rank:",arr)

<class 'numpy.ndarray'>
shape of a: (3,)
current value: 1 2 3
[5 2 3]
rank: 1


In [14]:
#2. 
b = np.array([[1, 2, 3], [4, 5, 6]])
print("shape of b:",b.shape)
print("current vales:",b[0, 0], b[0, 1], b[1, 0])
arr=np.linalg.matrix_rank([[1,2,3],[4,5,6]])
print("rank:",arr)

shape of b: (2, 3)
current vales: 1 2 4
rank: 2


In [19]:
#3.
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2),7)
d = np.random.random((2,2))
e = np.eye(2)
print("value of a:",a,"value of b:",b,"value of c:",c,"value of d:",d,"value of e:",e)

value of a: [[0. 0.]
 [0. 0.]] value of b: [[1. 1.]] value of c: [[7 7]
 [7 7]] value of d: [[0.30081859 0.88304631]
 [0.72058565 0.36528639]] value of e: [[1. 0.]
 [0. 1.]]


In [41]:
#4. Run the following
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#What are the shape of a and b? What are the values in b?
print("shape of a:",a.shape)
b = a[:2, 1:3]
print("shape of b:",b.shape)
print("values of b:",b)

shape of a: (3, 4)
shape of b: (2, 2)
values of b: [[2 3]
 [6 7]]


In [ ]:
#5. What does the last line print? Does modifying b modify the original array?
print(a[0, 1])

2


In [44]:
b[0, 0] = 77
print(a[0,1])

77


In [50]:
#6.
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 = a[1:2,:]
print("value or r1:",row_r1,"\nshape of r1:",row_r1.shape)
print("value or r2:",row_r2,"\nshape of r2:",row_r2.shape)
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print("value or r1:",col_r1,"\nshape of r1:",col_r1.shape)
print("value or r2:",col_r2,"\nshape of r2:",col_r2.shape)

value or r1: [5 6 7 8] 
shape of r1: (4,)
value or r2: [[5 6 7 8]] 
shape of r2: (1, 4)
value or r1: [ 2  6 10] 
shape of r1: (3,)
value or r2: [[ 2]
 [ 6]
 [10]] 
shape of r2: (3, 1)


In [51]:
#7.Run the following:Are the two printed arrays equivalent?
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))


[1 4 5]
[1 4 5]


In [57]:
#8.When using integer array indexing, you can duplicate several times the same element from the source array. Compare the following instructions:
a = np.array([[1,2],[3,4],[5,6]])
b = a[[0,0],[1,1]]
print("value of b:",b)
c = np.array([a[0,1], a[0, 1]])
print("value of c:",c)

value of b: [2 2]
value of c: [2 2]


In [61]:
#9. One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix. Run the following code
# What do you observe?
a= np.array([[1,2,3],[4,5,6], [7,8,9], [10, 11, 12]])
print("value of A:",a)
b = np.array([0,2,0,1])
print("value of B:",b)
print(a[np.arange(4),b])
a[np.arange(4),b]+=10
print("last value of A:",a)


value of A: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
value of B: [0 2 0 1]
[ 1  6  7 11]
last value of A: [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [75]:
#10.Run the following:
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a > 2)
# What is the result stored in bool_idx?
print("bool_index:",bool_idx)
#Run the following:
print("bool_index of a:",a[bool_idx])
print(a[a > 2])
print("shape:",a.shape)

bool_index: [[False False]
 [ True  True]
 [ True  True]]
bool_index of a: [3 4 5 6]
[3 4 5 6]
shape: (3, 2)


In [ ]:
#11.Datatypes
#What are the datatypes of x, y, z?
x = np.array([1, 2])
print("data type of x:",x.dtype)
y = np.array([1.0, 2.0])
print("data type of y:",y.dtype)
z = np.array([1, 2], dtype=np.int32)
print("data type of z:",z.dtype)

data type of x: int64
data type of y: float64
data type of z: int32


In [87]:
#12.
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print("adding x and y:",x + y)
print("adding with nump:",np.add(x,y))
print("subtracting:",x - y)
print("subtracting with numpy:",np.subtract(x,y))
print("Multiplying:",x*y)
print("multiplying with numpy:",np.multiply(x, y))
print("dividing:",x/y)
print("dividing with numpy:",(x,y))
print("square root of x:",np.sqrt(x))

adding x and y: [[ 6.  8.]
 [10. 12.]]
adding with nump: [[ 6.  8.]
 [10. 12.]]
subtracting: [[-4. -4.]
 [-4. -4.]]
subtracting with numpy: [[-4. -4.]
 [-4. -4.]]
Multiplying: [[ 5. 12.]
 [21. 32.]]
multiplying with numpy: [[ 5. 12.]
 [21. 32.]]
dividing: [[0.2        0.33333333]
 [0.42857143 0.5       ]]
dividing with numpy: (array([[1., 2.],
       [3., 4.]]), array([[5., 6.],
       [7., 8.]]))
square root of x: [[1.         1.41421356]
 [1.73205081 2.        ]]


In [89]:
#13.What are the mathematical operations performed in the snippet below?
v = np.array([9,10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v,w))

219
219


In [ ]:
#14. What are the mathematical operations performed in the snippet below?
x = np.array([[1,2],[3,4]])
print(x.dot(v))
print(np.dot(y,v))

[29 67]
[105. 143.]


In [129]:
#15. 
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [91]:
#16.
x = np.array([[1,2,3],[3,4,5]])
print(x)
print(x.T)

[[1 2 3]
 [3 4 5]]
[[1 3]
 [2 4]
 [3 5]]


In [96]:
#17. Broadcasting
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.zeros(x.shape)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j]=x[i,j]+v[j]
        print(y)


[[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 4.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 4.]
 [5. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 4.]
 [5. 5. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 4.]
 [5. 5. 7.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 4.]
 [5. 5. 7.]
 [8. 0. 0.]
 [0. 0. 0.]]
[[2. 2. 4.]
 [5. 5. 7.]
 [8. 8. 0.]
 [0. 0. 0.]]
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [ 0.  0.  0.]]
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11.  0.  0.]]
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11.  0.]]
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [98]:
#18.
# Repeat v to match the shape of x
w = np.tile(v, (4,1))
print(w)

# y is already defined as the result of broadcasting x + v
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


In [117]:
#19.
x = np.array([[1,2,3],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = x + v
print("value of y:",y)
v = np.array([1,2,3])
w = np.array([4,5])
r = np.reshape(v,(3,1))
print("value of v:",r)

value of y: [[ 2  2  4]
 [ 8  8 10]
 [11 11 13]]
value of v: [[1]
 [2]
 [3]]


In [115]:
#20.
x = np.array([[1,2,3],[4,5,6]])
x2 = v + x
x2

array([[2, 4, 6],
       [5, 7, 9]])

In [125]:
#21
w = np.array([4,5])
w = w.reshape(1,2)
w = np.array([4,5,6])
y = x+w.reshape(3,1)
print(y)

[[ 5  6  7]
 [12 13 14]
 [16 17 18]]


In [126]:
#22.
x = np.array([[1,2,3],[7,8,9],[10,11,12]])
y = x*2
y

array([[ 2,  4,  6],
       [14, 16, 18],
       [20, 22, 24]])